program
    = { statement } EOF ;

statement
    = declaration | assignment ;

declaration
    = "var" identifier [ ":" type ] [ "=" expression ] ";" ;

assignment
    = identifier "=" expression ";" ;

identifier
    = IDENTIFIER ;

type
    = "i32" | "i64" | "string" | "bool" ;

expression
    = primary | unary | binary ;

primary
    = literal | identifier | "(" expression ")" ;

unary
    = ( "-" | "!" ) expression ;

binary
    = expression operator expression ;

operator
    = "+" | "-" | "*" | "/" ;

literal
    = WHOLE_NUMBER | STRING_LITERAL | BOOLEAN_LITERAL ;