program
    = { statement } EOF ;

statement
    = declaration | assignment | conditional | iteration

declaration
    = "var" identifier [ ":" type ] [ "=" expression ] ";" ;

assignment
    = identifier "=" expression ";" ;

conditional
    = "if" expression "{" { statement } "}" { elseif } [ else ] ;

elseif
    = "else" "if" expression "{" { statement } "}" ;

else
    = "else" "{" { statement } "}" ;

iteration
    = "loop" "{" { statement } "}" ;

identifier
    = IDENTIFIER ;

type
    = "i32" | "i64" | "string" | "bool" ;

expression
    = primary | unary | binary ;

primary
    = literal | identifier | "(" expression ")" ;

unary
    = ( "-" | "!" ) expression ;

binary
    = expression operator expression ;

operator
    = "+" | "-" | "*" | "/" | "==" | "!=" | ">" | ">=" | "<" | "<=" ;

literal
    = WHOLE_NUMBER | STRING_LITERAL | BOOLEAN_LITERAL ;