program
    = { statement } EOF ;

statement
    = declaration ;

declaration
    = "var" identifier [ ":" type ] [ "=" expression ] ";" ;

identifier
    = IDENTIFIER ;

type
    = "i32" | "i64" | "string" | "bool" ;

expression
    = primary | binary ;

primary
    = literal | identifier

binary
    = expression operator expression ;

operator
    = "+" | "-" | "*" | "/" ;

literal
    = WHOLE_NUMBER | STRING_LITERAL | BOOLEAN_LITERAL ;